#Especifico en qué lenguaje estoy trabajando
language: node_js

#Especifico en qué versiones de ese lenguaje quiero testear:
node_js:
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - node

#Antes de instalar las dependencias, necesito tener instalado grunt:
before_install:
  - npm install -g grunt-cli

#Especifico el comando a ejecutar, en este caso el de ejecutar los tests:
script:
  - grunt test