version: 2.0
jobs:
  build:
    docker:
      - image: juancpineda97/laligastats
    steps:
      - checkout
      - run:
          name: Ejecutar tests en la imagen de docker
          command: docker run -t -v `pwd`:/test juancpineda97/laligastats

