#Elijo la versión a usar de CircleCI
version: 2.0
jobs:
  build:
    machine:
      #Indico que quiero usar la imagen de ubuntu, que viene con Docker instalado
      image: ubuntu-2004:202010-01
    steps:
        #Realiza comprobaciones del estado de los archivos, etc...
      - checkout
      - run: ls -l ./api_rest
        #Ejecuta los tests
      - run: docker run -t -v `pwd`:/test juancpineda97/laligastats